// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets\IconRekordboxConnected.png
var resourceIconRekordboxConnectedPngData []byte
var resourceIconRekordboxConnectedPng = &fyne.StaticResource{
	StaticName:    "assets\\IconRekordboxConnected.png",
	StaticContent: resourceIconRekordboxConnectedPngData,
}

//go:embed assets\IconRekordboxDisconnected.png
var resourceIconRekordboxDisconnectedPngData []byte
var resourceIconRekordboxDisconnectedPng = &fyne.StaticResource{
	StaticName:    "assets\\IconRekordboxDisconnected.png",
	StaticContent: resourceIconRekordboxDisconnectedPngData,
}

//go:embed assets\LinkLogo.png
var resourceLinkLogoPngData []byte
var resourceLinkLogoPng = &fyne.StaticResource{
	StaticName:    "assets\\LinkLogo.png",
	StaticContent: resourceLinkLogoPngData,
}

//go:embed assets\LinkLogoGlowing.png
var resourceLinkLogoGlowingPngData []byte
var resourceLinkLogoGlowingPng = &fyne.StaticResource{
	StaticName:    "assets\\LinkLogoGlowing.png",
	StaticContent: resourceLinkLogoGlowingPngData,
}

//go:embed assets\LinkLogoGray.png
var resourceLinkLogoGrayPngData []byte
var resourceLinkLogoGrayPng = &fyne.StaticResource{
	StaticName:    "assets\\LinkLogoGray.png",
	StaticContent: resourceLinkLogoGrayPngData,
}

//go:embed assets\font\Inter_28pt-Bold.ttf
var resourceInter28ptBoldTtfData []byte
var resourceInter28ptBoldTtf = &fyne.StaticResource{
	StaticName:    "assets\\font\\Inter_28pt-Bold.ttf",
	StaticContent: resourceInter28ptBoldTtfData,
}

//go:embed assets\font\Inter_28pt-BoldItalic.ttf
var resourceInter28ptBoldItalicTtfData []byte
var resourceInter28ptBoldItalicTtf = &fyne.StaticResource{
	StaticName:    "assets\\font\\Inter_28pt-BoldItalic.ttf",
	StaticContent: resourceInter28ptBoldItalicTtfData,
}

//go:embed assets\font\Inter_28pt-Italic.ttf
var resourceInter28ptItalicTtfData []byte
var resourceInter28ptItalicTtf = &fyne.StaticResource{
	StaticName:    "assets\\font\\Inter_28pt-Italic.ttf",
	StaticContent: resourceInter28ptItalicTtfData,
}

//go:embed assets\font\Inter_28pt-Regular.ttf
var resourceInter28ptRegularTtfData []byte
var resourceInter28ptRegularTtf = &fyne.StaticResource{
	StaticName:    "assets\\font\\Inter_28pt-Regular.ttf",
	StaticContent: resourceInter28ptRegularTtfData,
}

//go:embed assets\font\JetBrainsMono-Regular.ttf
var resourceJetBrainsMonoRegularTtfData []byte
var resourceJetBrainsMonoRegularTtf = &fyne.StaticResource{
	StaticName:    "assets\\font\\JetBrainsMono-Regular.ttf",
	StaticContent: resourceJetBrainsMonoRegularTtfData,
}
